# Generated by Django 3.2.6 on 2021-10-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=75, null=True, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc.member', verbose_name='Создатель счета')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='CheckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(blank=True, max_length=75, null=True, verbose_name='Объект траты')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание траты')),
                ('amount', models.FloatField(default=0.0, verbose_name='Сумма')),
                ('check_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc.check', verbose_name='Счет')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc.member', verbose_name='Участник счета')),
            ],
            options={
                'verbose_name': 'Трата по счету',
                'verbose_name_plural': 'Траты по счетам',
            },
        ),
        migrations.CreateModel(
            name='CheckMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc.check', verbose_name='Счет')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc.member', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник счета',
                'verbose_name_plural': 'Участники счетов',
            },
        ),
    ]
