# Generated by Django 3.2.6 on 2021-10-28 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0004_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='to_user',
        ),
        migrations.AddField(
            model_name='debt',
            name='to_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_member', to='poc.member', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='from_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_member', to='poc.member', verbose_name='Должник'),
        ),
    ]
